import React, { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext(null);

export const LANGUAGES = [
  { code: 'en', name: 'English' },
  { code: 'hi', name: 'Hindi' },
  { code: 'ta', name: 'Tamil' },
  { code: 'kn', name: 'Kannada' },
];

// Full translations for all UI text
export const TRANSLATIONS = {
  en: {
    // Sidebar
    appName: 'ECHORA',
    appTagline: 'Volunteer Network',
    navDashboard: 'Dashboard',
    navTasks: 'Task Board',
    navNGORequests: 'NGO Requests',
    navMap: 'Map View',
    navMeetups: 'Meetups',
    navImpact: 'Impact',
    navLeaderboard: 'Leaderboard',
    navNGOForm: 'Submit NGO Request',
    navProfile: 'My Profile',
    navSignOut: 'Sign Out',
    navNavigation: 'Navigation',
    pts: 'pts',
    toSilver: 'To Silver',
    toGold: 'To Gold',
    toPlatinum: 'To Platinum',
    left: 'left',
    yourRank: 'Your Rank',
    points: 'Points',
    // Navbar
    searchPlaceholder: 'Search tasks, NGOs, locations...',
    notifications: 'Notifications',
    lightMode: 'Light Mode',
    darkMode: 'Dark Mode',
    // Page Titles
    pageDashboard: 'Dashboard',
    pageTasks: 'Task Board',
    pageNGORequests: 'NGO Requests',
    pageNGOForm: 'Submit Request',
    pageMap: 'Map View',
    pageMeetups: 'Weekend Meetups',
    pageImpact: 'Impact Dashboard',
    pageLeaderboard: 'Leaderboard',
    pageProfile: 'My Profile',
    pageLogin: 'Login',
    pageSignup: 'Sign Up',
    // Common
    loading: 'Loading...',
    save: 'Save',
    cancel: 'Cancel',
    submit: 'Submit',
    edit: 'Edit',
    delete: 'Delete',
    view: 'View',
    apply: 'Apply',
    filter: 'Filter',
    sort: 'Sort',
    search: 'Search',
    close: 'Close',
    back: 'Back',
    next: 'Next',
    yes: 'Yes',
    no: 'No',
    error: 'Error',
    success: 'Success',
    warning: 'Warning',
    info: 'Info',
    // Voice Assistant
    voiceAssistant: 'Voice Assistant',
    voiceStatus: 'Voice Status',
    currentLanguage: 'Current Language',
    selectLanguage: 'Select Language',
    volume: 'Volume',
    speechRate: 'Speech Rate',
    voiceInput: 'Voice Input',
    listening: 'Listening...',
    showChat: 'Show Chat',
    hideChat: 'Hide Chat',
    stopSpeaking: 'Stop Speaking',
    aiVoiceChat: 'AI Voice Chat',
    askAnything: 'Ask me anything about ECHORA!',
    langSupported: 'I can answer in English, Hindi, Tamil, and Kannada',
    typeHere: 'Type here...',
    clearChat: 'Clear Chat',
    voiceNotAvailable: 'Voice Not Available',
    installVoices: 'To install voices',
    winSettingsPath: 'Windows Settings → Time & Language → Language → Add a language',
    // Dashboard
    greetingMorning: 'Good morning',
    greetingAfternoon: 'Good afternoon',
    greetingEvening: 'Good evening',
    welcome: 'Welcome,',
    volunteerRole: 'Volunteer',
    beginner: 'Beginner',
    tasksCompleted: 'Tasks Completed',
    pointsEarned: 'Points Earned',
    badgesEarned: 'Badges Earned',
    ngosHelped: 'NGOs Helped',
    tasksMatchedForYou: 'Tasks Matched For You',
    viewAll: 'View All →',
    upcomingMeetups: 'Upcoming Meetups',
    seeAll: 'See all',
    quickActions: 'Quick Actions',
    browseTasks: 'Browse Tasks',
    viewMap: 'View Map',
    impactStats: 'Impact Stats',
    platformImpact: 'Platform Impact',
    volunteers: 'Volunteers',
    tasksDone: 'Tasks Done',
    ngos: 'NGOs',
    cities: 'Cities',
    // Map
    mapVolunteers: 'Volunteers',
    mapNGOTasks: 'NGO Tasks',
    mapHeatmap: 'Heatmap',
    mapAllStates: 'All States',
    mapMyLocation: 'My Location',
    mapLegend: 'Legend',
    mapNearestTask: 'Nearest task to you',
    mapFlyTo: 'Fly to',
    mapShowingYourLocation: 'Showing your location',
    mapTip: 'Tip: Set your location in Profile to see your position on the map and find nearest tasks.',
    intermediate: 'Intermediate',
    expert: 'Expert',
    urgencyHigh: 'High',
    urgencyMedium: 'Medium',
    urgencyLow: 'Low',
    yourLocation: 'Your Location',
  },
  hi: {
    appName: 'ECHORA',
    appTagline: 'स्वयंसेवक नेटवर्क',
    navDashboard: 'डैशबोर्ड',
    navTasks: 'कार्य बोर्ड',
    navNGORequests: 'NGO अनुरोध',
    navMap: 'मानचित्र दृश्य',
    navMeetups: 'मिलन स्थल',
    navImpact: 'प्रभाव',
    navLeaderboard: 'लीडरबोर्ड',
    navNGOForm: 'NGO अनुरोध जमा करें',
    navProfile: 'मेरा प्रोफाइल',
    navSignOut: 'साइन आउट',
    navNavigation: 'मार्गदर्शन',
    pts: 'अंक',
    toSilver: 'सिल्वर तक',
    toGold: 'गोल्ड तक',
    toPlatinum: 'प्लैटिनम तक',
    left: 'बाकी',
    yourRank: 'आपकी रैंक',
    points: 'अंक',
    searchPlaceholder: 'कार्य, NGO, स्थान खोजें...',
    notifications: 'सूचनाएं',
    lightMode: 'लाइट मोड',
    darkMode: 'डार्क मोड',
    pageDashboard: 'डैशबोर्ड',
    pageTasks: 'कार्य बोर्ड',
    pageNGORequests: 'NGO अनुरोध',
    pageNGOForm: 'अनुरोध जमा करें',
    pageMap: 'मानचित्र दृश्य',
    pageMeetups: 'सप्ताहांत मिलन',
    pageImpact: 'प्रभाव डैशबोर्ड',
    pageLeaderboard: 'लीडरबोर्ड',
    pageProfile: 'मेरा प्रोफाइल',
    pageLogin: 'लॉगिन',
    pageSignup: 'साइन अप',
    loading: 'लोड हो रहा है...',
    save: 'सेव करें',
    cancel: 'रद्द करें',
    submit: 'जमा करें',
    edit: 'संपादित करें',
    delete: 'हटाएं',
    view: 'देखें',
    apply: 'आवेदन करें',
    filter: 'फ़िल्टर',
    sort: 'क्रमबद्ध',
    search: 'खोजें',
    close: 'बंद करें',
    back: 'वापस',
    next: 'अगला',
    yes: 'हाँ',
    no: 'नहीं',
    error: 'त्रुटि',
    success: 'सफल',
    warning: 'चेतावनी',
    info: 'जानकारी',
    voiceAssistant: 'ध्वनि सहायक',
    voiceStatus: 'ध्वनि स्थिति',
    currentLanguage: 'वर्तमान भाषा',
    selectLanguage: 'भाषा चुनें',
    volume: 'आवाज़',
    speechRate: 'बोलने की गति',
    voiceInput: 'ध्वनि इनपुट',
    listening: 'सुन रहा है...',
    showChat: 'चैट दिखाएं',
    hideChat: 'चैट छुपाएं',
    stopSpeaking: 'बोलना बंद करें',
    aiVoiceChat: 'AI ध्वनि चैट',
    askAnything: 'ECHORA के बारे में कुछ भी पूछें!',
    langSupported: 'मैं अंग्रेजी, हिंदी, तमिल और कन्नड़ में जवाब दे सकता हूँ',
    typeHere: 'यहाँ टाइप करें...',
    clearChat: 'चैट साफ़ करें',
    voiceNotAvailable: 'ध्वनि उपलब्ध नहीं',
    installVoices: 'ध्वनि स्थापित करने के लिए',
    winSettingsPath: 'Windows सेटिंग्स → समय और भाषा → भाषा → भाषा जोड़ें',
    greetingMorning: 'शुभ प्रभात',
    greetingAfternoon: 'शुभ दोपहर',
    greetingEvening: 'शुभ संध्या',
    welcome: 'स्वागत है,',
    volunteerRole: 'स्वयंसेवक',
    beginner: 'शुरुआती',
    tasksCompleted: 'पूरे किए गए कार्य',
    pointsEarned: 'अर्जित अंक',
    badgesEarned: 'अर्जित बैज',
    ngosHelped: 'मदद किए गए NGO',
    tasksMatchedForYou: 'आपके लिए मेल खाने वाले कार्य',
    viewAll: 'सभी देखें →',
    upcomingMeetups: 'आगामी मिलन',
    seeAll: 'सभी देखें',
    quickActions: 'त्वरित क्रियाएँ',
    browseTasks: 'कार्य ब्राउज़ करें',
    viewMap: 'मानचित्र देखें',
    impactStats: 'प्रभाव आँकड़े',
    platformImpact: 'मंच का प्रभाव',
    volunteers: 'स्वयंसेवक',
    tasksDone: 'पूरे किए गए कार्य',
    ngos: 'NGO',
    cities: 'शहर',
    // Map
    mapVolunteers: 'स्वयंसेवक',
    mapNGOTasks: 'NGO कार्य',
    mapHeatmap: 'हीटमैप',
    mapAllStates: 'सभी राज्य',
    mapMyLocation: 'मेरा स्थान',
    mapLegend: 'संकेत',
    mapNearestTask: 'आपके निकटतम कार्य:',
    mapFlyTo: 'वहां जाएं',
    mapShowingYourLocation: 'आपका स्थान दिखा रहा है',
    mapTip: 'सुझाव: मानचित्र पर अपनी स्थिति देखने और निकटतम कार्यों को खोजने के लिए प्रोफ़ाइल में अपना स्थान सेट करें।',
    intermediate: 'मध्यम',
    expert: 'विशेषज्ञ',
    urgencyHigh: 'उच्च',
    urgencyMedium: 'मध्यम',
    urgencyLow: 'कम',
    yourLocation: 'आपका स्थान',
  },
  ta: {
    appName: 'ECHORA',
    appTagline: 'தன்னார்வலர் வலையமைப்பு',
    navDashboard: 'டாஷ்போர்டு',
    navTasks: 'பணி பலகை',
    navNGORequests: 'NGO கோரிக்கைகள்',
    navMap: 'வரைபடம்',
    navMeetups: 'சந்திப்புகள்',
    navImpact: 'தாக்கம்',
    navLeaderboard: 'முன்னிலைப்படுத்தல்',
    navNGOForm: 'NGO கோரிக்கை சமர்ப்பிக்க',
    navProfile: 'என் சுயவிவரம்',
    navSignOut: 'வெளியேறு',
    navNavigation: 'வழிசெலுத்தல்',
    pts: 'புள்ளிகள்',
    toSilver: 'வெள்ளிக்கு',
    toGold: 'தங்கத்திற்கு',
    toPlatinum: 'பிளாட்டினத்திற்கு',
    left: 'மீதம்',
    yourRank: 'உங்கள் தரவரிசை',
    points: 'புள்ளிகள்',
    searchPlaceholder: 'பணிகள், NGO, இடங்களைத் தேடு...',
    notifications: 'அறிவிப்புகள்',
    lightMode: 'ஒளி பயன்முறை',
    darkMode: 'இருள் பயன்முறை',
    pageDashboard: 'டாஷ்போர்டு',
    pageTasks: 'பணி பலகை',
    pageNGORequests: 'NGO கோரிக்கைகள்',
    pageNGOForm: 'கோரிக்கை சமர்ப்பிக்க',
    pageMap: 'வரைபடம்',
    pageMeetups: 'வார இறுதி சந்திப்புகள்',
    pageImpact: 'தாக்கம் டாஷ்போர்டு',
    pageLeaderboard: 'முன்னிலைப்படுத்தல்',
    pageProfile: 'என் சுயவிவரம்',
    pageLogin: 'உள்நுழைவு',
    pageSignup: 'பதிவு செய்',
    loading: 'ஏற்றுகிறது...',
    save: 'சேமி',
    cancel: 'ரத்து செய்',
    submit: 'சமர்ப்பி',
    edit: 'திருத்து',
    delete: 'அழி',
    view: 'காண்க',
    apply: 'விண்ணப்பி',
    filter: 'வடிகட்டி',
    sort: 'வரிசைப்படுத்து',
    search: 'தேடு',
    close: 'மூடு',
    back: 'பின்',
    next: 'அடுத்து',
    yes: 'ஆம்',
    no: 'இல்லை',
    error: 'பிழை',
    success: 'வெற்றி',
    warning: 'எச்சரிக்கை',
    info: 'தகவல்',
    voiceAssistant: 'குரல் உதவியாளர்',
    voiceStatus: 'குரல் நிலை',
    currentLanguage: 'தற்போதைய மொழி',
    selectLanguage: 'மொழியைத் தேர்ந்தெடு',
    volume: 'ஒலி அளவு',
    speechRate: 'பேச்சு வேகம்',
    voiceInput: 'குரல் உள்ளீடு',
    listening: 'கேட்கிறது...',
    showChat: 'அரட்டையைக் காட்டு',
    hideChat: 'அரட்டையை மறை',
    stopSpeaking: 'பேசுவதை நிறுத்து',
    aiVoiceChat: 'AI குரல் அரட்டை',
    askAnything: 'ECHORA பற்றி எதையும் கேளுங்கள்!',
    langSupported: 'நான் ஆங்கிலம், இந்தி, தமிழ் மற்றும் கன்னடத்தில் பதிலளிக்க முடியும்',
    typeHere: 'இங்கே தட்டச்சு செய்...',
    clearChat: 'அரட்டையை அழி',
    voiceNotAvailable: 'குரல் கிடைக்கவில்லை',
    installVoices: 'குரல்களை நிறுவ',
    winSettingsPath: 'Windows அமைப்புகள் → நேரம் & மொழி → மொழி → மொழியைச் சேர்',
    greetingMorning: 'காலை வணக்கம்',
    greetingAfternoon: 'மதிய வணக்கம்',
    greetingEvening: 'மாலை வணக்கம்',
    welcome: 'வரவேற்கிறோம்,',
    volunteerRole: 'தன்னார்வலர்',
    beginner: 'தொடக்கக்காரர்',
    tasksCompleted: 'முடிக்கப்பட்ட பணிகள்',
    pointsEarned: 'பெறப்பட்ட புள்ளிகள்',
    badgesEarned: 'பெறப்பட்ட பேட்ஜ்கள்',
    ngosHelped: 'உதவப்பட்ட NGO-க்கள்',
    tasksMatchedForYou: 'உங்களுக்குப் பொருத்தமான பணிகள்',
    viewAll: 'அனைத்தையும் காண்க →',
    upcomingMeetups: 'நடைபெறவிருக்கும் சந்திப்புகள்',
    seeAll: 'அனைத்தையும் காண்க',
    quickActions: 'விரைவான செயல்கள்',
    browseTasks: 'பணிகளை உலாவு',
    viewMap: 'வரைபடம் காண்க',
    impactStats: 'தாக்க புள்ளிவிவரங்கள்',
    platformImpact: 'தளத்தின் தாக்கம்',
    volunteers: 'தன்னார்வலர்கள்',
    tasksDone: 'முடிக்கப்பட்ட பணிகள்',
    ngos: 'NGO-க்கள்',
    cities: 'நகரங்கள்',
    // Map
    mapVolunteers: 'தன்னார்வலர்கள்',
    mapNGOTasks: 'NGO பணிகள்',
    mapHeatmap: 'வெப்ப வரைபடம்',
    mapAllStates: 'அனைத்து மாநிலங்கள்',
    mapMyLocation: 'என் இடம்',
    mapLegend: 'குறிப்புகள்',
    mapNearestTask: 'உங்களுக்கு அருகிலுள்ள பணி:',
    mapFlyTo: 'அங்கே செல்',
    mapShowingYourLocation: 'உங்கள் இடத்தைக் காட்டுகிறது',
    mapTip: 'குறிப்பு: வரைபடத்தில் உங்கள் நிலையைக் காணவும் அருகிலுள்ள பணிகளைக் கண்டறியவும் சுயவிவரத்தில் உங்கள் இடத்தைச் சேர்க்கவும்.',
    intermediate: 'இடைநிலை',
    expert: 'நிபுணர்',
    urgencyHigh: 'அதிக',
    urgencyMedium: 'நடுத்தர',
    urgencyLow: 'குறைந்த',
    yourLocation: 'உங்கள் இடம்',
  },
  kn: {
    appName: 'ECHORA',
    appTagline: 'ಸ್ವಯಂಸೇವಕ ನೆಟ್‌ವರ್ಕ್',
    navDashboard: 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
    navTasks: 'ಕಾರ್ಯ ಬೋರ್ಡ್',
    navNGORequests: 'NGO ವಿನಂತಿಗಳು',
    navMap: 'ನಕ್ಷೆ ನೋಟ',
    navMeetups: 'ಸಮ್ಮೇಳನಗಳು',
    navImpact: 'ಪರಿಣಾಮ',
    navLeaderboard: 'ಲೀಡರ್‌ಬೋರ್ಡ್',
    navNGOForm: 'NGO ವಿನಂತಿ ಸಲ್ಲಿಸಿ',
    navProfile: 'ನನ್ನ ಪ್ರೊಫೈಲ್',
    navSignOut: 'ಸೈನ್ ಔಟ್',
    navNavigation: 'ಮಾರ್ಗದರ್ಶನ',
    pts: 'ಅಂಕಗಳು',
    toSilver: 'ಬೆಳ್ಳಿಗೆ',
    toGold: 'ಬಂಗಾರಕ್ಕೆ',
    toPlatinum: 'ಪ್ಲಾಟಿನಮ್‌ಗೆ',
    left: 'ಉಳಿದಿದೆ',
    yourRank: 'ನಿಮ್ಮ ಶ್ರೇಣಿ',
    points: 'ಅಂಕಗಳು',
    searchPlaceholder: 'ಕಾರ್ಯಗಳು, NGO, ಸ್ಥಳಗಳನ್ನು ಹುಡುಕಿ...',
    notifications: 'ಅಧಿಸೂಚನೆಗಳು',
    lightMode: 'ಲೈಟ್ ಮೋಡ್',
    darkMode: 'ಡಾರ್ಕ್ ಮೋಡ್',
    pageDashboard: 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
    pageTasks: 'ಕಾರ್ಯ ಬೋರ್ಡ್',
    pageNGORequests: 'NGO ವಿನಂತಿಗಳು',
    pageNGOForm: 'ವಿನಂತಿ ಸಲ್ಲಿಸಿ',
    pageMap: 'ನಕ್ಷೆ ನೋಟ',
    pageMeetups: 'ವಾರಾಂತ್ಯ ಸಮ್ಮೇಳನಗಳು',
    pageImpact: 'ಪರಿಣಾಮ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
    pageLeaderboard: 'ಲೀಡರ್‌ಬೋರ್ಡ್',
    pageProfile: 'ನನ್ನ ಪ್ರೊಫೈಲ್',
    pageLogin: 'ಲಾಗಿನ್',
    pageSignup: 'ಸೈನ್ ಅಪ್',
    loading: 'ಲೋಡ್ ಆಗುತ್ತಿದೆ...',
    save: 'ಉಳಿಸಿ',
    cancel: 'ರದ್ದು ಮಾಡಿ',
    submit: 'ಸಲ್ಲಿಸಿ',
    edit: 'ಸಂಪಾದಿಸಿ',
    delete: 'ಅಳಿಸಿ',
    view: 'ನೋಟ',
    apply: 'ಅಪ್ಲೈ',
    filter: 'ಫಿಲ್ಟರ್',
    sort: 'ವಿಂಗಡಿಸಿ',
    search: 'ಹುಡುಕಿ',
    close: 'ಮುಚ್ಚಿ',
    back: 'ಹಿಂದೆ',
    next: 'ಮುಂದೆ',
    yes: 'ಹೌದು',
    no: 'ಇಲ್ಲ',
    error: 'ದೋಷ',
    success: 'ಯಶಸ್ಸು',
    warning: 'ಎಚ್ಚರಿಕೆ',
    info: 'ಮಾಹಿತಿ',
    voiceAssistant: 'ಧ್ವನಿ ಸಹಾಯಕ',
    voiceStatus: 'ಧ್ವನಿ ಸ್ಥಿತಿ',
    currentLanguage: 'ಪ್ರಸ್ತುತ ಭಾಷೆ',
    selectLanguage: 'ಭಾಷೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ',
    volume: 'ಧ್ವನಿ',
    speechRate: 'ಮಾತಿನ ವೇಗ',
    voiceInput: 'ಧ್ವನಿ ಇನ್‌ಪುಟ್',
    listening: 'ಕೇಳುತ್ತಿದೆ...',
    showChat: 'ಚಾಟ್ ತೋರಿಸು',
    hideChat: 'ಚಾಟ್ ಮರೆಮಾಡು',
    stopSpeaking: 'ಮಾತನಾಡುವುದನ್ನು ನಿಲ್ಲಿಸು',
    aiVoiceChat: 'AI ಧ್ವನಿ ಚಾಟ್',
    askAnything: 'ECHORA ಬಗ್ಗೆ ಏನನ್ನಾದರೂ ಕೇಳಿ!',
    langSupported: 'ನಾನು ಇಂಗ್ಲೀಷ್, ಹಿಂದಿ, ತಮಿಳು ಮತ್ತು ಕನ್ನಡದಲ್ಲಿ ಉತ್ತರಿಸಬಲ್ಲೆ',
    typeHere: 'ಇಲ್ಲಿ ಟೈಪ್ ಮಾಡಿ...',
    clearChat: 'ಚಾಟ್ ಸ್ಪಷ್ಟಪಡಿಸಿ',
    voiceNotAvailable: 'ಧ್ವನಿ ಲಭ್ಯವಿಲ್ಲ',
    installVoices: 'ಧ್ವನಿಗಳನ್ನು ಸ್ಥಾಪಿಸಲು',
    winSettingsPath: 'Windows ಸೆಟ್ಟಿಂಗ್‌ಗಳು → ಸಮಯ & ಭಾಷೆ → ಭಾಷೆ → ಭಾಷೆಯನ್ನು ಸೇರಿಸಿ',
    greetingMorning: 'ಶುಭೋದಯ',
    greetingAfternoon: 'ಶುಭ ಮಧ್ಯಾಹ್ನ',
    greetingEvening: 'ಶುಭ ಸಂಜೆ',
    welcome: 'ಸ್ವಾಗತ,',
    volunteerRole: 'ಸ್ವಯಂಸೇವಕ',
    beginner: 'ಆರಂಭಿಕ',
    tasksCompleted: 'ಪೂರ್ಣಗೊಂಡ ಕಾರ್ಯಗಳು',
    pointsEarned: 'ಗಳಿಸಿದ ಅಂಕಗಳು',
    badgesEarned: 'ಗಳಿಸಿದ ಬ್ಯಾಡ್ಜ್‌ಗಳು',
    ngosHelped: 'ಸಹಾಯ ಮಾಡಿದ NGO ಗಳು',
    tasksMatchedForYou: 'ನಿಮಗಾಗಿ ಹೊಂದಿಕೆಯಾಗುವ ಕಾರ್ಯಗಳು',
    viewAll: 'ಎಲ್ಲವನ್ನೂ ವೀಕ್ಷಿಸಿ →',
    upcomingMeetups: 'ಮುಂಬರುವ ಸಮ್ಮೇಳನಗಳು',
    seeAll: 'ಎಲ್ಲವನ್ನೂ ನೋಡಿ',
    quickActions: 'ತ್ವರಿತ ಕ್ರಿಯೆಗಳು',
    browseTasks: 'ಕಾರ್ಯಗಳನ್ನು ಬ್ರೌಸ್ ಮಾಡಿ',
    viewMap: 'ನಕ್ಷೆ ವೀಕ್ಷಿಸಿ',
    impactStats: 'ಪರಿಣಾಮದ ಅಂಕಿಅಂಶಗಳು',
    platformImpact: 'ಪ್ಲಾಟ್‌ಫಾರ್ಮ್ ಪರಿಣಾಮ',
    volunteers: 'ಸ್ವಯಂಸೇವಕರು',
    tasksDone: 'ಪೂರ್ಣಗೊಂಡ ಕಾರ್ಯಗಳು',
    ngos: 'NGO ಗಳು',
    cities: 'ನಗರಗಳು',
    // Map
    mapVolunteers: 'स्वयंसेवक',
    mapNGOTasks: 'NGO ಕಾರ್ಯಗಳು',
    mapHeatmap: 'ಹೀಟ್‌ಮ್ಯಾಪ್',
    mapAllStates: 'ಎಲ್ಲಾ ರಾಜ್ಯಗಳು',
    mapMyLocation: 'ನನ್ನ ಸ್ಥಳ',
    mapLegend: 'ಸೂಚನೆ',
    mapNearestTask: 'ನಿಮಗೆ ಹತ್ತಿರದ ಕಾರ್ಯ:',
    mapFlyTo: 'ಅಲ್ಲಿಗೆ ಹೋಗಿ',
    mapShowingYourLocation: 'ನಿಮ್ಮ ಸ್ಥಳವನ್ನು ತೋರಿಸಲಾಗುತ್ತಿದೆ',
    mapTip: 'ಸಲಹೆ: ನಕ್ಷೆಯಲ್ಲಿ ನಿಮ್ಮ ಸ್ಥಾನವನ್ನು ನೋಡಲು ಮತ್ತು ಹತ್ತಿರದ ಕಾರ್ಯಗಳನ್ನು ಹುಡುಕಲು ಪ್ರೊಫೈಲ್‌ನಲ್ಲಿ ನಿಮ್ಮ ಸ್ಥಳವನ್ನು ಹೊಂದಿಸಿ.',
    intermediate: 'ಮಧ್ಯಂತರ',
    expert: 'ತಜ್ಞ',
    urgencyHigh: 'ಹೆಚ್ಚಿನ',
    urgencyMedium: 'ಮಧ್ಯಮ',
    urgencyLow: 'ಕಡಿಮೆ',
    yourLocation: 'ನಿಮ್ಮ ಸ್ಥಳ',
  },
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    const saved = localStorage.getItem('echora_language');
    return saved || 'en';
  });

  useEffect(() => {
    localStorage.setItem('echora_language', language);
    document.documentElement.lang = language === 'hi' ? 'hi-IN' : language === 'ta' ? 'ta-IN' : language === 'kn' ? 'kn-IN' : 'en';
  }, [language]);

  const t = (key) => {
    return TRANSLATIONS[language]?.[key] || TRANSLATIONS['en'][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, LANGUAGES }}>
      {children}
    </LanguageContext.Provider>
  );
};

// eslint-disable-next-line react-refresh/only-export-components
export const useLanguage = () => {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useLanguage must be used within LanguageProvider');
  return ctx;
};
